# Generated by Django 3.2.7 on 2021-09-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='item',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name',
            field=models.CharField(default='main', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='pounds', max_length=10),
        ),
    ]
