# Generated by Django 3.2.7 on 2021-09-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210921_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperequirement',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='reciperequirement',
            name='ingredient',
            field=models.ManyToManyField(to='inventory.Ingredient'),
        ),
    ]
