# Generated by Django 3.2.6 on 2021-09-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210921_2107'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('menu_item', 'timestamp')},
        ),
    ]
